apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist.fullname" . }}-mongo
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
      protocol: TCP
  selector:
    app: {{ include "todolist.fullname" . }}-mongo
